import type {
  SeedInquiry,
  SeedNotification,
  SeedReport,
  SeedThread,
  SeedVerificationRequest,
} from "./types";

/**
 * Inquiries double as the evidence trail behind review verification levels:
 * a review is only labelled VERIFIED_REVIEWER when the author has an inquiry
 * here that the owner responded to, scheduled or closed.
 */
export const INQUIRIES: SeedInquiry[] = [
  {
    property: "sunrise-lodge-self-contain-awka",
    student: "chi",
    type: "VIEWING_REQUEST",
    message: "Good day. Is the self-contain still available? I would like to come and see it on Saturday morning.",
    status: "CLOSED",
    ownerResponse: "Yes, it is available. Saturday 10am works — the caretaker will meet you at the gate.",
    daysAgo: 320,
  },
  {
    property: "sunrise-lodge-self-contain-awka",
    student: "kevin",
    type: "TOTAL_COST",
    message: "Please confirm the total first payment: rent, caution and any other charge. I want to avoid surprises.",
    status: "RESPONDED",
    ownerResponse: "Rent 250,000 plus 50,000 refundable caution. No agency fee and no inspection fee.",
    daysAgo: 250,
  },
  {
    property: "unizik-junction-shared-room-awka",
    student: "kevin",
    type: "AVAILABILITY",
    message: "Is there a free bed space this semester?",
    status: "RESPONDED",
    ownerResponse: "Two bed spaces left in Block A. 45,000 per session plus 10,000 caution.",
    daysAgo: 205,
  },
  {
    property: "unizik-junction-shared-room-awka",
    student: "aisha",
    type: "AVAILABILITY",
    message: "I am visiting Awka next month. Can I inspect before paying anything?",
    status: "RESPONDED",
    ownerResponse: "Of course. Inspect first — we never collect money before a visit.",
    daysAgo: 30,
  },
  {
    property: "cedar-court-2bedroom-flat-yaba",
    student: "tolu",
    type: "VIEWING_REQUEST",
    message: "I would like to inspect the flat before the new session. Is Thursday possible?",
    status: "VIEWING_SCHEDULED",
    ownerResponse: "Thursday 4pm confirmed. Bring a means of ID for the estate gate register.",
    viewingInDays: 3,
    daysAgo: 12,
  },
  {
    property: "cedar-court-2bedroom-flat-yaba",
    student: "bola",
    type: "TOTAL_COST",
    message: "What is the breakdown of rent, caution, agency and service charge?",
    status: "RESPONDED",
    ownerResponse: "Rent 900,000, caution 200,000, agency 90,000, service charge 60,000 per year.",
    daysAgo: 160,
  },
  {
    property: "akoka-hostel-room-block-b",
    student: "tolu",
    type: "AVAILABILITY",
    message: "Do you have a room in Block B for the coming session?",
    status: "CLOSED",
    ownerResponse: "Room B14 was free but has since been taken. I can put you on the waiting list.",
    daysAgo: 290,
  },
  {
    property: "akoka-hostel-room-block-b",
    student: "chi",
    type: "DISTANCE",
    message: "How long does it take to walk from the hostel to the faculty of engineering?",
    status: "RESPONDED",
    ownerResponse: "About 8 minutes on foot through the campus gate.",
    daysAgo: 130,
  },
  {
    property: "akoka-hostel-room-block-b",
    student: "grace",
    type: "TOTAL_COST",
    message: "Is the 15,000 service charge per session or per year? What does it cover?",
    status: "RESPONDED",
    ownerResponse: "Per session. It covers cleaning of common areas and the generator diesel.",
    daysAgo: 25,
  },
  {
    property: "parakin-self-contain-ile-ife",
    student: "yemi",
    type: "VIEWING_REQUEST",
    message: "Can I come and see the room this weekend?",
    status: "CLOSED",
    ownerResponse: "Come Saturday at 9am. Ask for the caretaker at the gate.",
    daysAgo: 350,
  },
  {
    property: "parakin-self-contain-ile-ife",
    student: "grace",
    type: "AVAILABILITY",
    message: "Is the self-contain still vacant?",
    status: "RESPONDED",
    ownerResponse: "It is vacant now. Rent is 200,000 per year with 40,000 caution.",
    daysAgo: 95,
  },
  {
    property: "kongo-single-room-zaria",
    student: "aisha",
    type: "OTHER",
    message: "Is the water tanker schedule fixed or does it change? I need to plan my storage.",
    status: "RESPONDED",
    ownerResponse: "Tuesdays and Fridays, usually by 7am. You should have at least two drums.",
    daysAgo: 330,
  },
  {
    property: "kongo-single-room-zaria",
    student: "zainab",
    type: "AVAILABILITY",
    message: "Is there a room free in the women-only section for next session?",
    status: "RESPONDED",
    ownerResponse: "One room will be free in two months. You can reserve it after inspection.",
    daysAgo: 640,
  },
  {
    property: "futa-gate-self-contain-akure",
    student: "grace",
    type: "VIEWING_REQUEST",
    message: "I would like to inspect before paying anything. When are you available?",
    status: "CLOSED",
    ownerResponse: "Any weekday after 3pm. Never pay before you inspect.",
    daysAgo: 410,
  },
  {
    property: "futa-gate-self-contain-akure",
    student: "halima",
    type: "TOTAL_COST",
    message: "Does the rent include the inverter and solar water heater, or are they charged separately?",
    status: "RESPONDED",
    ownerResponse: "Both are included in the 220,000. You only pay for power on your own meter.",
    daysAgo: 195,
  },
  {
    property: "ugbowo-3bedroom-apartment-benin",
    student: "halima",
    type: "TOTAL_COST",
    message: "Is the service charge payable yearly or monthly, and what does it cover?",
    status: "RESPONDED",
    ownerResponse: "Yearly, 80,000. It covers generator diesel, security and common area cleaning.",
    daysAgo: 360,
  },
  {
    property: "ugbowo-3bedroom-apartment-benin",
    student: "aisha",
    type: "VIEWING_REQUEST",
    message: "Three of us want to share. Can we inspect on Saturday?",
    status: "VIEWING_SCHEDULED",
    ownerResponse: "Saturday 11am is fine. Come with the other two so everyone sees it.",
    viewingInDays: 5,
    daysAgo: 255,
  },
  {
    property: "canaanland-self-contain-ota",
    student: "halima",
    type: "AVAILABILITY",
    message: "Is there a vacant self-contain for a fresher?",
    status: "RESPONDED",
    ownerResponse: "Yes, one is free from next month. 300,000 per year plus 60,000 caution.",
    daysAgo: 225,
  },
  {
    property: "sango-ota-2bedroom-bungalow",
    student: "chi",
    type: "DISTANCE",
    message: "How do I get to the Covenant gate from Sango Ota without a car?",
    status: "CLOSED",
    ownerResponse: "The shuttle stop is 5 minutes from the gate. It runs 6am to 8pm.",
    daysAgo: 315,
  },
  {
    property: "onuiyi-haven-room-nsukka-fully-let",
    student: "ndidi",
    type: "AVAILABILITY",
    message: "Is any room free at Onuiyi Haven this session?",
    status: "RESPONDED",
    ownerResponse: "Everything is occupied. I can add you to the waiting list for next session.",
    daysAgo: 440,
  },
  {
    property: "bariga-studio-near-unilag",
    student: "bola",
    type: "VIEWING_REQUEST",
    message: "Can I see the studio this week? I am currently in school.",
    status: "NEW",
    daysAgo: 1,
  },
  {
    property: "mayfair-single-room-ile-ife",
    student: "yemi",
    type: "AVAILABILITY",
    message: "Is the single room still available for the coming session?",
    status: "RESPONDED",
    ownerResponse: "Yes. Come and inspect first, then we can discuss payment.",
    daysAgo: 220,
  },
  {
    property: "ifite-suspicious-listing-awka-suspended",
    student: "chi",
    type: "AVAILABILITY",
    message: "The price seems too low for a furnished self-contain in Ifite. Is this listing genuine?",
    status: "NEW",
    daysAgo: 7,
  },
];

export const THREADS: SeedThread[] = [
  {
    a: "chi",
    b: "emeka",
    subject: "GENERAL",
    property: "sunrise-lodge-self-contain-awka",
    messages: [
      {
        from: "chi",
        body: "Good afternoon. I saw the Sunrise Lodge listing. Is the caution fee refundable when I move out?",
        hoursAgo: 52,
      },
      {
        from: "emeka",
        body: "Good afternoon. Yes, the 50,000 caution is refundable after inspection, minus anything outstanding on your meter.",
        hoursAgo: 50,
      },
      {
        from: "chi",
        body: "Thank you. I will come with my friend on Saturday to inspect before any payment.",
        hoursAgo: 49,
      },
      { from: "emeka", body: "That is the right way to do it. The caretaker will be there Saturday morning.", hoursAgo: 48 },
    ],
  },
  {
    a: "kevin",
    b: "tolu",
    subject: "ROOMMATE",
    messages: [
      {
        from: "kevin",
        body: "Hi, I saw your roommate profile. I am also looking for a two bedroom around Ifite. Are you still searching?",
        hoursAgo: 30,
      },
      {
        from: "tolu",
        body: "Hello. I am actually based in Lagos at UNILAG, so Ifite would not work for me — but my cousin at UNIZIK is looking.",
        hoursAgo: 28,
      },
      { from: "kevin", body: "No problem, thanks for the honest reply. They can message me here if interested.", hoursAgo: 27 },
    ],
  },
  {
    a: "halima",
    b: "segun",
    subject: "GENERAL",
    property: "cedar-court-2bedroom-flat-yaba",
    messages: [
      { from: "halima", body: "Please what is the total first payment for the Cedar Court flat?", hoursAgo: 10 },
      {
        from: "segun",
        body: "Rent 900,000, caution 200,000, agency 90,000 and service charge 60,000. All payable to the owner's account, never cash.",
        hoursAgo: 9,
      },
      { from: "halima", body: "Understood. I will inspect with my parents first.", hoursAgo: 8 },
    ],
  },
  {
    a: "grace",
    b: "aisha",
    subject: "ROOMMATE",
    messages: [
      { from: "grace", body: "Your profile says you keep early hours — same here. Do you study at home or outside?", hoursAgo: 6 },
      { from: "aisha", body: "Mostly at home in the morning, library in the evening. What is your budget range?", hoursAgo: 5 },
      { from: "grace", body: "Around 120,000 to 180,000 per year for my share. Let me know if that matches yours.", hoursAgo: 4 },
    ],
  },
  {
    a: "bola",
    b: "blessing",
    subject: "GENERAL",
    property: "akoka-hostel-room-block-b",
    messages: [
      { from: "bola", body: "Is there any room left in Block B for the coming session?", hoursAgo: 20 },
      { from: "blessing", body: "Block B is full. Block C has two rooms left at the same price.", hoursAgo: 19 },
      { from: "bola", body: "Please can I inspect Block C on Friday?", hoursAgo: 18 },
    ],
  },
];

export const FAVORITES: { user: SeedInquiry["student"]; property: string }[] = [
  { user: "chi", property: "sunrise-lodge-self-contain-awka" },
  { user: "chi", property: "parakin-self-contain-ile-ife" },
  { user: "chi", property: "canaanland-self-contain-ota" },
  { user: "kevin", property: "unizik-junction-shared-room-awka" },
  { user: "kevin", property: "sunrise-lodge-self-contain-awka" },
  { user: "tolu", property: "cedar-court-2bedroom-flat-yaba" },
  { user: "tolu", property: "akoka-hostel-room-block-b" },
  { user: "bola", property: "bariga-studio-near-unilag" },
  { user: "aisha", property: "kongo-single-room-zaria" },
  { user: "aisha", property: "ugbowo-3bedroom-apartment-benin" },
  { user: "grace", property: "futa-gate-self-contain-akure" },
  { user: "halima", property: "ugbowo-3bedroom-apartment-benin" },
  { user: "halima", property: "canaanland-self-contain-ota" },
  { user: "yemi", property: "mayfair-single-room-ile-ife" },
  { user: "ndidi", property: "onuiyi-haven-room-nsukka-fully-let" },
  { user: "zainab", property: "samaru-2bedroom-flat-zaria" },
];

export const SAVED_SEARCHES: { user: SeedInquiry["student"]; name: string; query: Record<string, unknown> }[] = [
  {
    user: "chi",
    name: "Self-contain near UNIZIK under ₦250k",
    query: { university: "UNIZIK", propertyType: "SELF_CONTAIN", maxRent: 250000, maxDistanceKm: 3, sort: "newest" },
  },
  {
    user: "kevin",
    name: "Shared rooms in Awka",
    query: { university: "UNIZIK", city: "Awka", propertyType: "SHARED_ROOM", sort: "rent_asc" },
  },
  {
    user: "tolu",
    name: "Two bedroom flats in Yaba with security",
    query: { university: "UNILAG", neighborhood: "Yaba", bedrooms: 2, amenities: ["CCTV", "SECURITY"], sort: "newest" },
  },
  {
    user: "halima",
    name: "Verified listings near Covenant",
    query: { university: "COVENANT", verified: true, sort: "highest_rated" },
  },
  {
    user: "grace",
    name: "FUTA self-contain with prepaid meter",
    query: { university: "FUTA", propertyType: "SELF_CONTAIN", amenities: ["PREPAID_METER"], maxRent: 250000 },
  },
];

export const VERIFICATION_REQUESTS: SeedVerificationRequest[] = [
  {
    user: "emeka",
    type: "IDENTITY",
    status: "VERIFIED",
    note: "Government ID and a utility bill matched the account name. Reviewed by admin.",
    daysAgo: 375,
  },
  {
    user: "musa",
    type: "OWNERSHIP",
    status: "VERIFIED",
    note: "Certificate of occupancy for the Parakin property verified against the listing address.",
    daysAgo: 150,
  },
  { user: "tunde", type: "IDENTITY", status: "VERIFIED", note: "ID verified during the FUTA site visit.", daysAgo: 330 },
  { user: "funke", type: "IDENTITY", status: "PENDING", daysAgo: 6 },
  { user: "segun", type: "AGENCY_LICENSE", status: "PENDING", daysAgo: 3 },
  {
    user: "chidinma",
    type: "IDENTITY",
    status: "REJECTED",
    note: "Submitted ID did not match the registered account name.",
    daysAgo: 20,
  },
];

export const REPORTS: SeedReport[] = [
  {
    targetType: "PROPERTY",
    target: { kind: "property", slug: "mayfair-single-room-ile-ife" },
    reason: "MISLEADING_INFORMATION",
    details: "The listing says water is from a well but the photos show a tanker. Please confirm the actual water source.",
    reporter: "yemi",
    status: "OPEN",
    daysAgo: 3,
  },
  {
    targetType: "PROPERTY",
    target: { kind: "property", slug: "ifite-suspicious-listing-awka-suspended" },
    reason: "SUSPICIOUS_PAYMENT_REQUEST",
    details: "Asked for a 20,000 naira commitment fee by transfer before allowing an inspection.",
    anonymous: true,
    status: "UNDER_REVIEW",
    daysAgo: 8,
  },
  {
    targetType: "USER",
    target: { kind: "user", user: "chidinma" },
    reason: "SUSPICIOUS_PAYMENT_REQUEST",
    details: "Requested an inspection fee by transfer before I was allowed to see the property at Odenigbo.",
    anonymous: true,
    status: "OPEN",
    daysAgo: 9,
  },
  {
    targetType: "MESSAGE",
    target: { kind: "message" },
    reason: "SPAM",
    details: "Repeated unsolicited messages after I asked to stop.",
    reporter: "chi",
    status: "RESOLVED",
    resolution: "Warning issued to the sender. No content was removed — the student's messages remain visible to them.",
    daysAgo: 5,
  },
];

export const NOTIFICATIONS: SeedNotification[] = [
  {
    user: "emeka",
    type: "REVIEW_RECEIVED",
    title: "New review submitted",
    body: 'A student submitted a review for "Sunrise Lodge — self-contain in Ifite, Awka". It will appear after moderation.',
    link: "/dashboard/landlord/reviews",
    daysAgo: 4,
  },
  {
    user: "emeka",
    type: "INQUIRY_NEW",
    title: "New inquiry",
    body: "A student asked about the total cost of your Sunrise Lodge listing.",
    link: "/dashboard/landlord/inquiries",
    read: true,
    daysAgo: 250,
  },
  {
    user: "segun",
    type: "MESSAGE_NEW",
    title: "New message",
    body: "Halima Yusuf sent you a message about Cedar Court.",
    link: "/dashboard/messages",
    daysAgo: 0,
  },
  {
    user: "chi",
    type: "NEW_MATCHING_PROPERTY",
    title: "New listing matches your saved search",
    body: 'A self-contain near UNIZIK matches "Self-contain near UNIZIK under ₦250k".',
    link: "/properties/sunrise-lodge-self-contain-awka",
    daysAgo: 6,
  },
  {
    user: "chi",
    type: "ROOMMATE_MATCH",
    title: "Possible roommate match",
    body: "Kevin Okon is looking for a roommate in Ifite with a similar budget.",
    link: "/roommates",
    daysAgo: 2,
  },
  {
    user: "chi",
    type: "ACCOUNT_ALERT",
    title: "New sign-in to your account",
    body: "We noticed a sign-in from a new device. If this was not you, change your password.",
    link: "/dashboard/settings",
    read: true,
    daysAgo: 15,
  },
  {
    user: "kevin",
    type: "REVIEW_RESPONSE",
    title: "Owner responded to your review",
    body: "The owner of Sunrise Lodge replied publicly to your review.",
    link: "/properties/sunrise-lodge-self-contain-awka",
    read: true,
    daysAgo: 12,
  },
  {
    user: "funke",
    type: "VERIFICATION_STATUS",
    title: "Verification documents received",
    body: "Your identity documents are in the review queue. You will be notified when a decision is made.",
    link: "/dashboard/verification",
    daysAgo: 6,
  },
  {
    user: "chidinma",
    type: "VERIFICATION_STATUS",
    title: "Verification not approved",
    body: "The ID you submitted did not match your account name. You can submit a different document.",
    link: "/dashboard/verification",
    daysAgo: 19,
  },
  {
    user: "tunde",
    type: "LISTING_APPROVED",
    title: "Listing approved",
    body: 'Your listing "Self-contain by FUTA north gate, Akure" is live in search results.',
    link: "/properties/futa-gate-self-contain-akure",
    read: true,
    daysAgo: 66,
  },
  {
    user: "chidinma",
    type: "LISTING_REJECTED",
    title: "Listing not approved",
    body:
      'Your listing "Self-contain at Odenigbo, Nsukka" was not approved: the photos did not match the stated address.',
    link: "/dashboard/landlord/properties",
    daysAgo: 44,
  },
  {
    user: "chidinma",
    type: "SUSPICIOUS_ACTIVITY",
    title: "Listing suspended pending review",
    body: 'Your listing "Furnished self-contain in Ifite" was suspended after reports. Contact support to resolve it.',
    link: "/dashboard/landlord/properties",
    daysAgo: 8,
  },
  {
    user: "admin",
    type: "SUSPICIOUS_ACTIVITY",
    title: "Reports need review",
    body: "Two reports are waiting in the admin queue, including a suspicious payment request.",
    link: "/admin/reports",
    daysAgo: 9,
  },
  {
    user: "admin",
    type: "ACCOUNT_ALERT",
    title: "Listings awaiting review",
    body: "One submitted listing is waiting for approval.",
    link: "/admin/properties",
    daysAgo: 3,
  },
];
