import type { SeedNeighborhood, SeedUniversity } from "./types";

export const UNIVERSITIES: SeedUniversity[] = [
  {
    key: "UNIZIK",
    name: "Nnamdi Azikiwe University",
    shortName: "UNIZIK",
    slug: "nnamdi-azikiwe-university",
    city: "Awka",
    state: "Anambra",
    campuses: [
      { name: "Main Campus", slug: "main-campus", latitude: 6.1813, longitude: 7.028, city: "Awka" },
      { name: "Nnewi Campus", slug: "nnewi-campus", latitude: 6.0167, longitude: 6.9167, city: "Nnewi" },
    ],
    faculties: [
      { name: "Engineering", departments: ["Computer Engineering", "Civil Engineering"] },
      { name: "Medicine", departments: ["Medicine and Surgery", "Nursing Science"] },
      { name: "Management Sciences", departments: ["Accountancy", "Business Administration"] },
    ],
  },
  {
    key: "UNN",
    name: "University of Nigeria, Nsukka",
    shortName: "UNN",
    slug: "university-of-nigeria-nsukka",
    city: "Nsukka",
    state: "Enugu",
    campuses: [
      { name: "Nsukka Campus", slug: "nsukka-campus", latitude: 6.8561, longitude: 7.3927, city: "Nsukka" },
      { name: "Enugu Campus", slug: "enugu-campus", latitude: 6.4402, longitude: 7.4876, city: "Enugu" },
    ],
    faculties: [
      { name: "Physical Sciences", departments: ["Computer Science", "Geology"] },
      { name: "Law", departments: ["Law"] },
    ],
  },
  {
    key: "UNILAG",
    name: "University of Lagos",
    shortName: "UNILAG",
    slug: "university-of-lagos",
    city: "Lagos",
    state: "Lagos",
    campuses: [{ name: "Akoka Campus", slug: "akoka-campus", latitude: 6.5167, longitude: 3.3917, city: "Lagos" }],
    faculties: [
      { name: "Engineering", departments: ["Electrical and Electronics Engineering"] },
      { name: "Social Sciences", departments: ["Mass Communication"] },
    ],
  },
  {
    key: "OAU",
    name: "Obafemi Awolowo University",
    shortName: "OAU",
    slug: "obafemi-awolowo-university",
    city: "Ile-Ife",
    state: "Osun",
    campuses: [{ name: "Main Campus", slug: "main-campus", latitude: 7.4813, longitude: 4.5149, city: "Ile-Ife" }],
  },
  {
    key: "ABU",
    name: "Ahmadu Bello University",
    shortName: "ABU",
    slug: "ahmadu-bello-university",
    city: "Zaria",
    state: "Kaduna",
    campuses: [
      { name: "Samaru Campus", slug: "samaru-campus", latitude: 11.1561, longitude: 7.6545, city: "Zaria" },
      { name: "Kongo Campus", slug: "kongo-campus", latitude: 11.1473, longitude: 7.6766, city: "Zaria" },
    ],
  },
  {
    key: "COVENANT",
    name: "Covenant University",
    shortName: "COVENANT",
    slug: "covenant-university",
    city: "Ota",
    state: "Ogun",
    campuses: [{ name: "Canaanland Campus", slug: "canaanland-campus", latitude: 6.675, longitude: 3.16, city: "Ota" }],
  },
  {
    key: "FUTA",
    name: "Federal University of Technology, Akure",
    shortName: "FUTA",
    slug: "federal-university-of-technology-akure",
    city: "Akure",
    state: "Ondo",
    campuses: [{ name: "Main Campus", slug: "main-campus", latitude: 7.3027, longitude: 5.1414, city: "Akure" }],
  },
  {
    key: "UNIBEN",
    name: "University of Benin",
    shortName: "UNIBEN",
    slug: "university-of-benin",
    city: "Benin City",
    state: "Edo",
    campuses: [{ name: "Ugbowo Campus", slug: "ugbowo-campus", latitude: 6.3676, longitude: 5.6149, city: "Benin City" }],
  },
];

export const NEIGHBORHOODS: SeedNeighborhood[] = [
  { name: "Ifite", slug: "ifite-awka", city: "Awka", state: "Anambra", latitude: 6.196, longitude: 7.067 },
  { name: "UNIZIK Junction", slug: "unizik-junction-awka", city: "Awka", state: "Anambra", latitude: 6.1911, longitude: 7.0338 },
  { name: "Aroma Junction", slug: "aroma-junction-awka", city: "Awka", state: "Anambra", latitude: 6.2101, longitude: 7.0712 },
  { name: "Odenigbo", slug: "odenigbo-nsukka", city: "Nsukka", state: "Enugu", latitude: 6.8581, longitude: 7.4001 },
  { name: "Onuiyi Haven", slug: "onuiyi-haven-nsukka", city: "Nsukka", state: "Enugu", latitude: 6.847, longitude: 7.3955 },
  { name: "Akoka", slug: "akoka-lagos", city: "Lagos", state: "Lagos", latitude: 6.5181, longitude: 3.3951 },
  { name: "Bariga", slug: "bariga-lagos", city: "Lagos", state: "Lagos", latitude: 6.5371, longitude: 3.3967 },
  { name: "Yaba", slug: "yaba-lagos", city: "Lagos", state: "Lagos", latitude: 6.5083, longitude: 3.3756 },
  { name: "Mayfair", slug: "mayfair-ile-ife", city: "Ile-Ife", state: "Osun", latitude: 7.4901, longitude: 4.5263 },
  { name: "Parakin", slug: "parakin-ile-ife", city: "Ile-Ife", state: "Osun", latitude: 7.4721, longitude: 4.5011 },
  { name: "Samaru", slug: "samaru-zaria", city: "Zaria", state: "Kaduna", latitude: 11.1565, longitude: 7.6533 },
  { name: "Kongo", slug: "kongo-zaria", city: "Zaria", state: "Kaduna", latitude: 11.1475, longitude: 7.6769 },
  { name: "FUTA Gate", slug: "futa-gate-akure", city: "Akure", state: "Ondo", latitude: 7.3055, longitude: 5.1401 },
  { name: "Obanikoro", slug: "obanikoro-akure", city: "Akure", state: "Ondo", latitude: 7.2905, longitude: 5.1533 },
  { name: "Ugbowo", slug: "ugbowo-benin", city: "Benin City", state: "Edo", latitude: 6.3691, longitude: 5.6171 },
  { name: "Canaanland", slug: "canaanland-ota", city: "Ota", state: "Ogun", latitude: 6.6742, longitude: 3.1611 },
  { name: "Sango Ota", slug: "sango-ota", city: "Ota", state: "Ogun", latitude: 6.6921, longitude: 3.2103 },
];
