import type { SeedRoommate, SeedUser } from "./types";

export const ADMIN_EMAIL = process.env.SEED_ADMIN_EMAIL || "admin@studentnest.test";
export const ADMIN_PASSWORD = process.env.SEED_ADMIN_PASSWORD || "Admin!2345";
export const STUDENT_PASSWORD = "Student!2345";
export const OWNER_PASSWORD = "Owner!2345";

/**
 * Demo accounts only. Every address uses the reserved .test TLD so nothing can
 * be delivered to a real mailbox, and all documents referenced by verification
 * rows are placeholders.
 */
export const USERS: SeedUser[] = [
  { key: "admin", email: ADMIN_EMAIL, name: "StudentNest Admin", role: "ADMIN", password: ADMIN_PASSWORD, emailVerified: true, createdAtDaysAgo: 420 },
  {
    key: "emeka",
    email: "emeka.owner@studentnest.test",
    name: "Emeka Nwachukwu",
    role: "LANDLORD",
    password: OWNER_PASSWORD,
    phone: "+2348031234567",
    emailVerified: true,
    createdAtDaysAgo: 380,
    bio: "Owns two blocks of student rooms in Ifite, Awka. Has let to UNIZIK students for ten years.",
  },
  {
    key: "funke",
    email: "funke.owner@studentnest.test",
    name: "Funke Adeyemi",
    role: "LANDLORD",
    password: OWNER_PASSWORD,
    phone: "+2348029876543",
    createdAtDaysAgo: 40,
    bio: "Landlord in Bariga, Lagos. Identity documents submitted and awaiting review.",
  },
  {
    key: "musa",
    email: "musa.owner@studentnest.test",
    name: "Musa Ibrahim",
    role: "LANDLORD",
    password: OWNER_PASSWORD,
    phone: "+2348055512345",
    emailVerified: true,
    createdAtDaysAgo: 300,
    bio: "Owns student rooms near the ABU Samaru gate and a self-contain in Ile-Ife.",
  },
  {
    key: "chidinma",
    email: "chidinma.owner@studentnest.test",
    name: "Chidinma Okafor",
    role: "LANDLORD",
    password: OWNER_PASSWORD,
    phone: "+2347061122334",
    createdAtDaysAgo: 260,
    bio: "Lets an apartment in Ugbowo, Benin City to UNIBEN students, and manages one listing as an agent.",
  },
  {
    key: "tunde",
    email: "tunde.owner@studentnest.test",
    name: "Tunde Bakare",
    role: "LANDLORD",
    password: OWNER_PASSWORD,
    phone: "+2348133344455",
    emailVerified: true,
    createdAtDaysAgo: 340,
    bio: "Owns a bungalow in Sango Ota and a self-contain by the FUTA north gate.",
  },
  {
    key: "blessing",
    email: "blessing.caretaker@studentnest.test",
    name: "Blessing Eze",
    role: "AGENT",
    password: OWNER_PASSWORD,
    phone: "+2347012233445",
    emailVerified: true,
    createdAtDaysAgo: 200,
    bio: "Caretaker at Akoka Hostel. Handles viewings, keys and repairs on site.",
  },
  {
    key: "segun",
    email: "segun.agent@studentnest.test",
    name: "Segun Oladipo",
    role: "AGENT",
    password: OWNER_PASSWORD,
    phone: "+2348099988877",
    createdAtDaysAgo: 90,
    bio: "Estate agent working Yaba and Akoka. Agency licence submitted for review.",
  },
  {
    key: "chi",
    email: "chi.student@studentnest.test",
    name: "Chiamaka Uzo",
    role: "STUDENT",
    password: STUDENT_PASSWORD,
    gender: "FEMALE",
    university: "UNIZIK",
    campus: "main-campus",
    faculty: "Management Sciences",
    department: "Accountancy",
    level: "300",
    emailVerified: true,
    createdAtDaysAgo: 330,
    bio: "Accountancy student looking for a quiet self-contain within walking distance of campus.",
  },
  {
    key: "tolu",
    email: "tolu.student@studentnest.test",
    name: "Tolu Adewale",
    role: "STUDENT",
    password: STUDENT_PASSWORD,
    gender: "MALE",
    university: "UNILAG",
    campus: "akoka-campus",
    faculty: "Engineering",
    department: "Electrical and Electronics Engineering",
    level: "400",
    emailVerified: true,
    createdAtDaysAgo: 390,
    bio: "Final year engineering student. Needs stable power for project work.",
  },
  {
    key: "aisha",
    email: "aisha.student@studentnest.test",
    name: "Aisha Bello",
    role: "STUDENT",
    password: STUDENT_PASSWORD,
    gender: "FEMALE",
    university: "ABU",
    campus: "samaru-campus",
    level: "200",
    emailVerified: true,
    createdAtDaysAgo: 340,
    bio: "Looking for a shared room near Samaru with dependable water.",
  },
  {
    key: "ndidi",
    email: "ndidi.student@studentnest.test",
    name: "Ndidi Eze",
    role: "STUDENT",
    password: STUDENT_PASSWORD,
    gender: "FEMALE",
    university: "UNN",
    campus: "nsukka-campus",
    level: "200",
    createdAtDaysAgo: 430,
    bio: "UNN student. Prefers furnished rooms close to Odenigbo.",
  },
  {
    key: "kevin",
    email: "kevin.student@studentnest.test",
    name: "Kevin Okon",
    role: "STUDENT",
    password: STUDENT_PASSWORD,
    gender: "MALE",
    university: "UNIZIK",
    campus: "main-campus",
    faculty: "Engineering",
    department: "Computer Engineering",
    level: "200",
    emailVerified: true,
    createdAtDaysAgo: 250,
    bio: "Wants a roommate for a two bedroom flat around Ifite. Budget about 150k per year each.",
  },
  {
    key: "grace",
    email: "grace.student@studentnest.test",
    name: "Grace Adamu",
    role: "STUDENT",
    password: STUDENT_PASSWORD,
    gender: "FEMALE",
    university: "FUTA",
    campus: "main-campus",
    level: "300",
    emailVerified: true,
    createdAtDaysAgo: 410,
    bio: "FUTA student near the north gate. Early riser, keeps a tidy room.",
  },
  {
    key: "yemi",
    email: "yemi.student@studentnest.test",
    name: "Yemi Solarin",
    role: "STUDENT",
    password: STUDENT_PASSWORD,
    gender: "MALE",
    university: "OAU",
    campus: "main-campus",
    level: "300",
    createdAtDaysAgo: 230,
    bio: "OAU student looking for a shared or single room in Mayfair.",
  },
  {
    key: "halima",
    email: "halima.student@studentnest.test",
    name: "Halima Yusuf",
    role: "STUDENT",
    password: STUDENT_PASSWORD,
    gender: "FEMALE",
    university: "COVENANT",
    campus: "canaanland-campus",
    level: "100",
    emailVerified: true,
    createdAtDaysAgo: 360,
    bio: "Fresher at Covenant. Needs a self-contain with water and security.",
  },
  {
    key: "bola",
    email: "bola.student@studentnest.test",
    name: "Bola Ajayi",
    role: "STUDENT",
    password: STUDENT_PASSWORD,
    gender: "MALE",
    university: "UNILAG",
    campus: "akoka-campus",
    level: "200",
    createdAtDaysAgo: 170,
    bio: "Studies at night, plays football at the weekend.",
  },
  {
    key: "zainab",
    email: "zainab.student@studentnest.test",
    name: "Zainab Sani",
    role: "STUDENT",
    password: STUDENT_PASSWORD,
    gender: "FEMALE",
    university: "ABU",
    campus: "kongo-campus",
    level: "400",
    emailVerified: true,
    createdAtDaysAgo: 620,
    bio: "Final year student at Kongo. Quiet, prefers early nights.",
  },
];

export const ROOMMATES: SeedRoommate[] = [
  {
    key: "chi",
    university: "UNIZIK",
    campus: "main-campus",
    locations: ["Ifite", "UNIZIK Junction"],
    budgetMin: 120000,
    budgetMax: 200000,
    roomType: "SELF_CONTAIN",
    desiredRoommates: 1,
    cleanliness: "VERY_TIDY",
    sleepSchedule: "EARLY_BIRD",
    studyHabits: "STUDIES_AT_HOME",
    socialPreference: "OCCASIONALLY_SOCIAL",
    noiseTolerance: "LOW",
    moveInDays: 30,
    bio: "Accountancy student. I keep my space tidy and I am usually asleep by 10:30pm during the semester.",
    weights: { budget: 30, location: 25, moveIn: 15, lifestyle: 30 },
  },
  {
    key: "kevin",
    university: "UNIZIK",
    campus: "main-campus",
    locations: ["Ifite", "Aroma Junction"],
    budgetMin: 100000,
    budgetMax: 180000,
    roomType: "FLAT",
    desiredRoommates: 1,
    cleanliness: "BALANCED",
    sleepSchedule: "NIGHT_OWL",
    studyHabits: "STUDIES_AT_HOME",
    socialPreference: "OCCASIONALLY_SOCIAL",
    noiseTolerance: "MEDIUM",
    moveInDays: 30,
    bio: "Computer engineering, 200 level. I code late with headphones on, so I need someone who does not mind a lamp being on.",
  },
  {
    key: "tolu",
    university: "UNILAG",
    campus: "akoka-campus",
    locations: ["Akoka", "Yaba"],
    budgetMin: 300000,
    budgetMax: 500000,
    roomType: "FLAT",
    desiredRoommates: 1,
    cleanliness: "BALANCED",
    sleepSchedule: "NIGHT_OWL",
    studyHabits: "MIXED",
    socialPreference: "VERY_SOCIAL",
    noiseTolerance: "HIGH",
    moveInDays: 45,
    bio: "Final year engineering. Project work means odd hours. I play football on Saturdays and host friends occasionally.",
    weights: { budget: 20, location: 30, moveIn: 20, lifestyle: 30 },
  },
  {
    key: "bola",
    university: "UNILAG",
    campus: "akoka-campus",
    locations: ["Bariga", "Akoka"],
    budgetMin: 250000,
    budgetMax: 450000,
    roomType: "SHARED_ROOM",
    desiredRoommates: 2,
    cleanliness: "RELAXED",
    sleepSchedule: "FLEXIBLE",
    studyHabits: "STUDIES_OUTSIDE",
    socialPreference: "VERY_SOCIAL",
    noiseTolerance: "HIGH",
    moveInDays: 40,
    bio: "Easy going. I study in the library and sleep at home. Looking for two people to split a room or a small flat.",
  },
  {
    key: "aisha",
    university: "ABU",
    campus: "samaru-campus",
    locations: ["Samaru"],
    budgetMin: 40000,
    budgetMax: 90000,
    roomType: "SHARED_ROOM",
    desiredRoommates: 1,
    genderPreference: "FEMALE",
    cleanliness: "VERY_TIDY",
    sleepSchedule: "EARLY_BIRD",
    studyHabits: "STUDIES_AT_HOME",
    socialPreference: "QUIET_PRIVATE",
    noiseTolerance: "LOW",
    moveInDays: 60,
    bio: "I need quiet for studying and I keep my side of the room very neat. Non-smoker.",
  },
  {
    key: "zainab",
    university: "ABU",
    campus: "kongo-campus",
    locations: ["Kongo", "Samaru"],
    budgetMin: 50000,
    budgetMax: 100000,
    roomType: "SINGLE_ROOM",
    desiredRoommates: 1,
    cleanliness: "BALANCED",
    sleepSchedule: "EARLY_BIRD",
    studyHabits: "MIXED",
    socialPreference: "QUIET_PRIVATE",
    noiseTolerance: "LOW",
    moveInDays: 20,
    bio: "Final year. Moving out soon, so my dates are flexible within the next month.",
  },
  {
    key: "grace",
    university: "FUTA",
    campus: "main-campus",
    locations: ["FUTA Gate", "Obanikoro"],
    budgetMin: 120000,
    budgetMax: 220000,
    roomType: "SELF_CONTAIN",
    desiredRoommates: 1,
    cleanliness: "VERY_TIDY",
    sleepSchedule: "EARLY_BIRD",
    studyHabits: "STUDIES_AT_HOME",
    socialPreference: "OCCASIONALLY_SOCIAL",
    noiseTolerance: "LOW",
    moveInDays: 25,
    bio: "300 level. I would rather walk to lectures than pay for transport every day.",
    weights: { budget: 25, location: 30, moveIn: 15, lifestyle: 30 },
  },
  {
    key: "halima",
    university: "COVENANT",
    campus: "canaanland-campus",
    locations: ["Canaanland", "Sango Ota"],
    budgetMin: 200000,
    budgetMax: 350000,
    roomType: "SELF_CONTAIN",
    desiredRoommates: 1,
    genderPreference: "FEMALE",
    cleanliness: "BALANCED",
    sleepSchedule: "FLEXIBLE",
    studyHabits: "MIXED",
    socialPreference: "OCCASIONALLY_SOCIAL",
    noiseTolerance: "MEDIUM",
    moveInDays: 35,
    bio: "Fresher. My parents want water and security confirmed before I move in, so a verified listing matters to me.",
  },
  {
    key: "yemi",
    university: "OAU",
    campus: "main-campus",
    locations: ["Mayfair", "Parakin"],
    budgetMin: 70000,
    budgetMax: 150000,
    roomType: "SINGLE_ROOM",
    desiredRoommates: 1,
    cleanliness: "RELAXED",
    sleepSchedule: "NIGHT_OWL",
    studyHabits: "STUDIES_OUTSIDE",
    socialPreference: "VERY_SOCIAL",
    noiseTolerance: "HIGH",
    moveInDays: 50,
    bio: "300 level. I am out most evenings and sleep late, so I match best with someone on a similar rhythm.",
  },
];
