import type { SeedProperty } from "./types";

/** Demo listings, part 2 — includes moderation-queue states (draft, rejected, suspended, fully let). */
export const PROPERTIES_B: SeedProperty[] = [
  {
    slug: "kongo-single-room-zaria",
    title: "Single room for a female student, Kongo",
    description:
      "Single room in the women-only section of a compound near the ABU Kongo campus. The owner prefers a first or second year student. Water is delivered by tanker twice a week into a compound tank.",
    houseRules: "Female occupants only in this section. Male visitors are received in the common parlour only.",
    owner: "chidinma",
    providerType: "LANDLORD",
    status: "ACTIVE",
    verificationStatus: "PENDING",
    propertyType: "SINGLE_ROOM",
    rentAmount: 70000,
    rentPeriod: "PER_YEAR",
    cautionDeposit: 15000,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 1,
    furnishing: "UNFURNISHED",
    university: "ABU",
    campus: "kongo-campus",
    neighborhood: "kongo-zaria",
    areaName: "Kongo, Zaria",
    city: "Zaria",
    state: "Kaduna",
    latitude: 11.1475,
    longitude: 7.6769,
    distanceKmToCampus: 0.8,
    addressLine: "12 Kongo Road, Zaria",
    createdAtDaysAgo: 17,
    amenities: ["WATER", "ELECTRICITY", "SHARED_FACILITIES", "SECURITY"],
    features: ["Women-only section", "Tanker water twice weekly"],
    images: 2,
    condition: {
      electricityAvailable: true,
      waterSource: "TANK",
      internetType: "MOBILE_NETWORK",
      securityFeatures: ["GATE"],
      electricityReliability: 2,
      waterReliability: 2,
      networkQuality: 2,
      roadCondition: 3,
      noiseLevel: 2,
      cleanliness: 3,
    },
  },
  {
    slug: "futa-gate-self-contain-akure",
    title: "Self-contain by FUTA north gate, Akure",
    description:
      "Self-contain with a sitting area, one bedroom and an en-suite bathroom, roughly 700m from the FUTA north gate. Solar water heating and a small inverter for lights are included. An earlier verification attempt was rejected because the submitted photos showed a different building; a fresh site visit confirmed this property.",
    owner: "tunde",
    providerType: "LANDLORD",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    verificationNote: "Second attempt verified: admin matched the address line, meter number and photos during a site visit.",
    rejectionReason: "First attempt rejected — the submitted photos showed a different building from the listed address.",
    propertyType: "SELF_CONTAIN",
    rentAmount: 220000,
    rentPeriod: "PER_YEAR",
    cautionDeposit: 50000,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 2,
    furnishing: "PARTIALLY_FURNISHED",
    university: "FUTA",
    campus: "main-campus",
    neighborhood: "futa-gate-akure",
    areaName: "FUTA North Gate, Akure",
    city: "Akure",
    state: "Ondo",
    latitude: 7.3055,
    longitude: 5.1401,
    distanceKmToCampus: 0.7,
    addressLine: "4 Gate Road, Akure",
    isFeatured: true,
    createdAtDaysAgo: 70,
    amenities: ["WATER", "ELECTRICITY", "SOLAR", "PREPAID_METER", "TILED_FLOOR", "EN_SUITE", "PARKING"],
    features: ["Solar water heater", "Small inverter for lights", "Separate reading area"],
    images: 4,
    condition: {
      electricityAvailable: true,
      solarAvailable: true,
      prepaidMeter: true,
      waterSource: "BOREHOLE",
      internetType: "FIBRE",
      securityFeatures: ["FENCED_COMPOUND", "GATE"],
      electricityReliability: 4,
      waterReliability: 4,
      networkQuality: 4,
      roadCondition: 4,
      noiseLevel: 2,
      cleanliness: 5,
      floodRisk: "LOW",
    },
  },
  {
    slug: "obanikoro-shared-room-akure",
    title: "Shared room in Obanikoro, Akure",
    description:
      "Two bed spaces in a shared room with a common kitchen and bathroom. Popular with FUTA students who want to split rent. Water is drawn from a compound borehole.",
    owner: "tunde",
    providerType: "LANDLORD",
    status: "ACTIVE",
    verificationStatus: "PENDING",
    propertyType: "SHARED_ROOM",
    rentAmount: 50000,
    rentPeriod: "PER_SESSION",
    cautionDeposit: 10000,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 2,
    furnishing: "UNFURNISHED",
    university: "FUTA",
    campus: "main-campus",
    neighborhood: "obanikoro-akure",
    areaName: "Obanikoro, Akure",
    city: "Akure",
    state: "Ondo",
    latitude: 7.2905,
    longitude: 5.1533,
    distanceKmToCampus: 2.2,
    addressLine: "31 Obanikoro Street, Akure",
    createdAtDaysAgo: 5,
    amenities: ["WATER", "ELECTRICITY", "SHARED_FACILITIES", "KITCHEN"],
    features: ["Rent is per bed space", "Compound borehole"],
    images: 2,
    condition: {
      electricityAvailable: true,
      waterSource: "BOREHOLE",
      internetType: "MOBILE_NETWORK",
      securityFeatures: ["GATE"],
      electricityReliability: 2,
      waterReliability: 3,
      networkQuality: 3,
      roadCondition: 2,
      noiseLevel: 3,
      cleanliness: 3,
      floodRisk: "MEDIUM",
    },
  },
  {
    slug: "ugbowo-3bedroom-apartment-benin",
    title: "3 bedroom apartment in Ugbowo, Benin City",
    description:
      "Spacious three bedroom apartment on the second floor of a gated block in Ugbowo, close to the UNIBEN campus gate. Suitable for three or four students sharing. There is a standby generator for common areas and a borehole with a treatment tank.",
    owner: "chidinma",
    providerType: "LANDLORD",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    verificationNote: "Ownership documents verified; admin confirmed the property exists at the listed address.",
    propertyType: "APARTMENT",
    rentAmount: 850000,
    rentPeriod: "PER_YEAR",
    cautionDeposit: 150000,
    serviceCharge: 80000,
    bedrooms: 3,
    bathrooms: 3,
    maxOccupants: 5,
    furnishing: "UNFURNISHED",
    university: "UNIBEN",
    campus: "ugbowo-campus",
    neighborhood: "ugbowo-benin",
    areaName: "Ugbowo, Benin City",
    city: "Benin City",
    state: "Edo",
    latitude: 6.3691,
    longitude: 5.6171,
    distanceKmToCampus: 1.2,
    addressLine: "Flat 2A, Ugbowo Heights, Benin City",
    createdAtDaysAgo: 51,
    amenities: ["WATER", "ELECTRICITY", "GENERATOR", "SECURITY", "CCTV", "FENCED_COMPOUND", "PARKING", "KITCHEN", "BALCONY"],
    features: ["Standby generator for common areas", "Treated borehole water", "Gated estate with CCTV"],
    images: 5,
    condition: {
      electricityAvailable: true,
      generatorAvailable: true,
      waterSource: "BOREHOLE",
      internetType: "FIBRE",
      securityFeatures: ["CCTV", "SECURITY_PERSONNEL", "FENCED_COMPOUND", "GATE"],
      electricityReliability: 3,
      waterReliability: 4,
      networkQuality: 4,
      roadCondition: 3,
      noiseLevel: 3,
      cleanliness: 4,
      floodRisk: "MEDIUM",
    },
  },
  {
    slug: "canaanland-self-contain-ota",
    title: "Self-contain near Covenant Canaanland",
    description:
      "Self-contain about 1.5km from the Covenant University gate with a direct shuttle route. Includes a bathroom, small kitchen and wardrobe. Power is on a shared meter split between three rooms.",
    owner: "tunde",
    providerType: "LANDLORD",
    status: "ACTIVE",
    verificationStatus: "PENDING",
    propertyType: "SELF_CONTAIN",
    rentAmount: 300000,
    rentPeriod: "PER_YEAR",
    cautionDeposit: 60000,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 2,
    furnishing: "PARTIALLY_FURNISHED",
    university: "COVENANT",
    campus: "canaanland-campus",
    neighborhood: "canaanland-ota",
    areaName: "Canaanland, Ota",
    city: "Ota",
    state: "Ogun",
    latitude: 6.6742,
    longitude: 3.1611,
    distanceKmToCampus: 1.5,
    addressLine: "8 Idiroko Road, Ota",
    createdAtDaysAgo: 21,
    amenities: ["WATER", "ELECTRICITY", "WARDROBE", "KITCHEN", "FENCED_COMPOUND"],
    features: ["Shuttle stop two minutes away", "Shared meter across three rooms"],
    images: 3,
    condition: {
      electricityAvailable: true,
      waterSource: "BOREHOLE",
      internetType: "MOBILE_NETWORK",
      securityFeatures: ["FENCED_COMPOUND", "GATE"],
      electricityReliability: 3,
      waterReliability: 3,
      networkQuality: 3,
      roadCondition: 3,
      noiseLevel: 2,
      cleanliness: 4,
      floodRisk: "LOW",
    },
  },
  {
    slug: "sango-ota-2bedroom-bungalow",
    title: "2 bedroom bungalow in Sango Ota",
    description:
      "Detached two bedroom bungalow with a small garden and parking space in Sango Ota. Suited to Covenant students with a car, or those comfortable using the shuttle route. Water comes from a borehole with an overhead tank.",
    owner: "tunde",
    providerType: "LANDLORD",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    verificationNote: "Identity and property ownership verified by admin.",
    propertyType: "BUNGALOW",
    rentAmount: 1200000,
    rentPeriod: "PER_YEAR",
    cautionDeposit: 200000,
    agencyFee: 60000,
    bedrooms: 2,
    bathrooms: 2,
    maxOccupants: 4,
    furnishing: "UNFURNISHED",
    university: "COVENANT",
    campus: "canaanland-campus",
    neighborhood: "sango-ota",
    areaName: "Sango Ota, Ogun",
    city: "Ota",
    state: "Ogun",
    latitude: 6.6921,
    longitude: 3.2103,
    distanceKmToCampus: 4.3,
    addressLine: "17 Sango Ota Express Road, Ota",
    createdAtDaysAgo: 96,
    amenities: ["WATER", "ELECTRICITY", "PARKING", "KITCHEN", "FENCED_COMPOUND", "SECURITY", "LAUNDRY"],
    features: ["Detached bungalow", "Private garden", "Parking for two cars"],
    images: 4,
    condition: {
      electricityAvailable: true,
      prepaidMeter: true,
      waterSource: "BOREHOLE",
      internetType: "WIFI",
      securityFeatures: ["FENCED_COMPOUND", "GATE"],
      electricityReliability: 3,
      waterReliability: 4,
      networkQuality: 4,
      roadCondition: 4,
      noiseLevel: 3,
      cleanliness: 4,
      floodRisk: "LOW",
    },
  },
  {
    slug: "odenigbo-self-contain-nsukka-not-approved",
    title: "Self-contain at Odenigbo, Nsukka (not approved)",
    description:
      "Submitted as a self-contain at Odenigbo. The StudentNest team did not approve it: the photos did not match the address given and the submitter could not show evidence of authority to let the property. It stays in the database so the decision and its reason remain visible to admins.",
    owner: "chidinma",
    providerType: "AGENT",
    status: "REJECTED",
    verificationStatus: "REJECTED",
    rejectionReason: "Photos did not match the stated address and no evidence of authority to let the property was provided.",
    propertyType: "SELF_CONTAIN",
    rentAmount: 160000,
    rentPeriod: "PER_YEAR",
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 2,
    furnishing: "UNFURNISHED",
    university: "UNN",
    campus: "nsukka-campus",
    neighborhood: "odenigbo-nsukka",
    areaName: "Odenigbo, Nsukka",
    city: "Nsukka",
    state: "Enugu",
    latitude: 6.8581,
    longitude: 7.4001,
    distanceKmToCampus: 1.0,
    addressLine: "2 Odenigbo Layout, Nsukka",
    createdAtDaysAgo: 45,
    amenities: ["WATER", "ELECTRICITY"],
    features: [],
    images: 2,
    condition: {
      electricityAvailable: true,
      waterSource: "WELL",
      internetType: "NONE",
      securityFeatures: [],
      electricityReliability: 2,
      waterReliability: 2,
      networkQuality: 2,
      roadCondition: 2,
      noiseLevel: 3,
      cleanliness: 3,
    },
  },
  {
    slug: "onuiyi-haven-room-nsukka-fully-let",
    title: "Room at Onuiyi Haven, Nsukka (fully let)",
    description:
      "Single room in a shared compound at Onuiyi Haven. All rooms are currently occupied, so the listing stays public and students can join the waiting list for the next session.",
    owner: "emeka",
    providerType: "CARETAKER",
    status: "RENTED_OUT",
    verificationStatus: "VERIFIED",
    verificationNote: "Verified during the previous session; status set to RENTED_OUT by the owner.",
    propertyType: "SINGLE_ROOM",
    rentAmount: 80000,
    rentPeriod: "PER_YEAR",
    cautionDeposit: 20000,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 1,
    furnishing: "UNFURNISHED",
    university: "UNN",
    campus: "nsukka-campus",
    neighborhood: "onuiyi-haven-nsukka",
    areaName: "Onuiyi Haven, Nsukka",
    city: "Nsukka",
    state: "Enugu",
    latitude: 6.847,
    longitude: 7.3955,
    distanceKmToCampus: 1.3,
    addressLine: "9 Onuiyi Haven Road, Nsukka",
    availableNow: false,
    availableFromDaysAhead: 120,
    createdAtDaysAgo: 140,
    amenities: ["WATER", "ELECTRICITY", "FENCED_COMPOUND", "SHARED_FACILITIES"],
    features: ["Waiting list open for next session"],
    images: 2,
    condition: {
      electricityAvailable: true,
      waterSource: "BOREHOLE",
      internetType: "MOBILE_NETWORK",
      securityFeatures: ["FENCED_COMPOUND"],
      electricityReliability: 2,
      waterReliability: 3,
      networkQuality: 3,
      roadCondition: 3,
      noiseLevel: 2,
      cleanliness: 3,
      floodRisk: "LOW",
    },
  },
  {
    slug: "aroma-junction-self-contain-draft-awka",
    title: "Self-contain near Aroma Junction (draft)",
    description:
      "Owner's unfinished listing for a new self-contain block near Aroma Junction. It has not been submitted for review, so it is invisible to students.",
    owner: "emeka",
    providerType: "LANDLORD",
    status: "DRAFT",
    verificationStatus: "PENDING",
    propertyType: "SELF_CONTAIN",
    rentAmount: 280000,
    rentPeriod: "PER_YEAR",
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 2,
    furnishing: "UNFURNISHED",
    university: "UNIZIK",
    campus: "main-campus",
    neighborhood: "aroma-junction-awka",
    areaName: "Aroma Junction, Awka",
    city: "Awka",
    state: "Anambra",
    latitude: 6.2101,
    longitude: 7.0712,
    distanceKmToCampus: 3.4,
    addressLine: "6 Aroma Junction Road, Awka",
    createdAtDaysAgo: 2,
    amenities: ["WATER", "ELECTRICITY"],
    features: ["Photos still to be uploaded"],
    images: 1,
    condition: {
      electricityAvailable: true,
      waterSource: "BOREHOLE",
      internetType: "MOBILE_NETWORK",
      securityFeatures: ["GATE"],
      electricityReliability: 3,
      waterReliability: 3,
      noiseLevel: 3,
      cleanliness: 4,
      floodRisk: "UNKNOWN",
    },
  },
  {
    slug: "ifite-suspicious-listing-awka-suspended",
    title: "Furnished self-contain in Ifite (suspended)",
    description:
      "Listed at well below the market rate for a furnished self-contain in Ifite and requesting payment before inspection. Suspended by an admin pending investigation after two reports.",
    owner: "chidinma",
    providerType: "AGENT",
    status: "SUSPENDED",
    verificationStatus: "SUSPENDED",
    rejectionReason: "Suspended: price far below market rate combined with requests for payment before inspection.",
    propertyType: "SELF_CONTAIN",
    rentAmount: 60000,
    rentPeriod: "PER_YEAR",
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 2,
    furnishing: "FURNISHED",
    university: "UNIZIK",
    campus: "main-campus",
    neighborhood: "ifite-awka",
    areaName: "Ifite, Awka",
    city: "Awka",
    state: "Anambra",
    latitude: 6.1975,
    longitude: 7.0688,
    distanceKmToCampus: 1.9,
    locationApproximate: true,
    addressLine: "88 Ifite Road, Awka",
    createdAtDaysAgo: 10,
    amenities: ["WATER", "ELECTRICITY", "FURNITURE", "AIR_CONDITIONING", "INTERNET"],
    features: ["Fully furnished", "Free wifi claimed"],
    images: 2,
    condition: {
      electricityAvailable: true,
      waterSource: "OTHER",
      internetType: "WIFI",
      securityFeatures: [],
      electricityReliability: 5,
      waterReliability: 5,
      networkQuality: 5,
      roadCondition: 5,
      noiseLevel: 1,
      cleanliness: 5,
      floodRisk: "LOW",
    },
  },
];
