import type { SeedProperty } from "./types";

/**
 * Demo listings, part 1. Slugs double as the SEO URLs used by the public site
 * (e.g. /properties/sunrise-lodge-self-contain-awka).
 */
export const PROPERTIES_A: SeedProperty[] = [
  {
    slug: "sunrise-lodge-self-contain-awka",
    title: "Sunrise Lodge — self-contain in Ifite, Awka",
    description:
      "Single-room self-contain with its own kitchenette and bathroom, about a 20 minute walk from the UNIZIK main gate. The compound is fenced with a gate that closes at 11pm, and each room has its own prepaid meter so you only pay for the power you use. Borehole water is pumped into overhead tanks daily.",
    houseRules:
      "No overnight visitors without caretaker approval. Keep the compound drain clear during rain. Quiet hours after 10pm on weekdays.",
    owner: "emeka",
    providerType: "LANDLORD",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    verificationNote: "Admin visited the property on Ifite Road and confirmed room count, prepaid meters and the borehole.",
    propertyType: "SELF_CONTAIN",
    rentAmount: 250000,
    rentPeriod: "PER_YEAR",
    cautionDeposit: 50000,
    agencyFee: 0,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 2,
    furnishing: "UNFURNISHED",
    university: "UNIZIK",
    campus: "main-campus",
    neighborhood: "ifite-awka",
    areaName: "Ifite, Awka",
    city: "Awka",
    state: "Anambra",
    latitude: 6.196,
    longitude: 7.067,
    distanceKmToCampus: 1.8,
    addressLine: "14 Ifite Road, Awka, Anambra",
    isFeatured: true,
    createdAtDaysAgo: 62,
    amenities: ["WATER", "ELECTRICITY", "PREPAID_METER", "FENCED_COMPOUND", "SECURITY", "TILED_FLOOR", "EN_SUITE", "PARKING"],
    features: ["Own kitchenette", "Prepaid meter per room", "Overhead water tank", "Tiled compound"],
    images: 4,
    condition: {
      electricityAvailable: true,
      prepaidMeter: true,
      waterSource: "BOREHOLE",
      internetType: "MOBILE_NETWORK",
      securityFeatures: ["FENCED_COMPOUND", "GATE"],
      electricityReliability: 3,
      waterReliability: 4,
      networkQuality: 3,
      roadCondition: 3,
      noiseLevel: 2,
      cleanliness: 4,
      floodRisk: "LOW",
    },
  },
  {
    slug: "unizik-junction-shared-room-awka",
    title: "Shared student room at UNIZIK Junction",
    description:
      "Two-per-room shared accommodation directly opposite the UNIZIK junction shuttle stop. Bathrooms and kitchen are shared between four rooms. Water comes from a well with a pump, and a small generator covers common area lighting only.",
    houseRules: "Rent covers one bed space. No cooking in the room — use the shared kitchen.",
    owner: "emeka",
    providerType: "LANDLORD",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    verificationNote: "Ownership documents and an on-site visit confirmed by admin.",
    propertyType: "SHARED_ROOM",
    rentAmount: 45000,
    rentPeriod: "PER_SESSION",
    cautionDeposit: 10000,
    bedrooms: 1,
    bathrooms: 2,
    maxOccupants: 2,
    furnishing: "PARTIALLY_FURNISHED",
    university: "UNIZIK",
    campus: "main-campus",
    neighborhood: "unizik-junction-awka",
    areaName: "UNIZIK Junction, Awka",
    city: "Awka",
    state: "Anambra",
    latitude: 6.1911,
    longitude: 7.0338,
    distanceKmToCampus: 0.6,
    locationApproximate: true,
    addressLine: "3 Junction Close, Awka, Anambra",
    createdAtDaysAgo: 40,
    amenities: ["WATER", "ELECTRICITY", "GENERATOR", "SHARED_FACILITIES", "KITCHEN", "FURNITURE"],
    features: ["Bunk beds provided", "Shared kitchen", "Five minutes to the shuttle stop"],
    images: 3,
    condition: {
      electricityAvailable: true,
      generatorAvailable: true,
      waterSource: "WELL",
      internetType: "MOBILE_NETWORK",
      securityFeatures: ["GATE"],
      electricityReliability: 2,
      waterReliability: 3,
      networkQuality: 3,
      roadCondition: 2,
      noiseLevel: 4,
      cleanliness: 3,
      floodRisk: "MEDIUM",
    },
  },
  {
    slug: "cedar-court-2bedroom-flat-yaba",
    title: "Cedar Court — 2 bedroom flat, Yaba",
    description:
      "Second floor two bedroom flat in a gated block off Herbert Macaulay Way. Inverter backup covers lights and fans, and the estate has round-the-clock security with CCTV at the entrance. Suited to two or three UNILAG students sharing.",
    houseRules: "No pets. Visitors sign in at the gate. Service charge is paid quarterly.",
    owner: "segun",
    providerType: "AGENT",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    verificationNote: "Agency licence and the owner's mandate letter were verified by admin.",
    propertyType: "FLAT",
    rentAmount: 900000,
    rentPeriod: "PER_YEAR",
    cautionDeposit: 200000,
    agencyFee: 90000,
    serviceCharge: 60000,
    bedrooms: 2,
    bathrooms: 2,
    maxOccupants: 4,
    furnishing: "PARTIALLY_FURNISHED",
    university: "UNILAG",
    campus: "akoka-campus",
    neighborhood: "yaba-lagos",
    areaName: "Yaba, Lagos",
    city: "Lagos",
    state: "Lagos",
    latitude: 6.5083,
    longitude: 3.3756,
    distanceKmToCampus: 2.4,
    addressLine: "Flat 2B, Cedar Court, Herbert Macaulay Way, Yaba",
    availableNow: false,
    availableFromDaysAhead: 21,
    isFeatured: true,
    createdAtDaysAgo: 25,
    amenities: ["WATER", "ELECTRICITY", "CCTV", "SECURITY", "FENCED_COMPOUND", "PARKING", "KITCHEN", "BALCONY", "AIR_CONDITIONING", "TILED_FLOOR"],
    features: ["Inverter backup for lights and fans", "Fitted kitchen", "24 hour estate security", "Lift access"],
    images: 5,
    condition: {
      electricityAvailable: true,
      generatorAvailable: true,
      prepaidMeter: true,
      waterSource: "BOREHOLE",
      internetType: "FIBRE",
      securityFeatures: ["CCTV", "SECURITY_PERSONNEL", "FENCED_COMPOUND", "GATE"],
      electricityReliability: 4,
      waterReliability: 4,
      networkQuality: 5,
      roadCondition: 4,
      noiseLevel: 3,
      cleanliness: 4,
      floodRisk: "MEDIUM",
    },
  },
  {
    slug: "bariga-studio-near-unilag",
    title: "Studio apartment in Bariga, near UNILAG",
    description:
      "Compact studio with a bathroom and small kitchen area, three bus stops from the Akoka campus gate. The owner is still completing identity verification, so StudentNest has not verified this listing yet.",
    owner: "funke",
    providerType: "LANDLORD",
    status: "ACTIVE",
    verificationStatus: "PENDING",
    propertyType: "STUDIO",
    rentAmount: 450000,
    rentPeriod: "PER_YEAR",
    cautionDeposit: 100000,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 1,
    furnishing: "FURNISHED",
    university: "UNILAG",
    campus: "akoka-campus",
    neighborhood: "bariga-lagos",
    areaName: "Bariga, Lagos",
    city: "Lagos",
    state: "Lagos",
    latitude: 6.5371,
    longitude: 3.3967,
    distanceKmToCampus: 3.1,
    addressLine: "9 Pedro Road, Bariga, Lagos",
    createdAtDaysAgo: 12,
    amenities: ["WATER", "ELECTRICITY", "FURNITURE", "KITCHEN", "WARDROBE", "AIR_CONDITIONING"],
    features: ["Bed and mattress included", "Built-in wardrobe", "Air conditioner"],
    images: 3,
    condition: {
      electricityAvailable: true,
      prepaidMeter: true,
      waterSource: "TANK",
      internetType: "WIFI",
      securityFeatures: ["GATE"],
      electricityReliability: 3,
      waterReliability: 2,
      networkQuality: 4,
      roadCondition: 3,
      noiseLevel: 4,
      cleanliness: 3,
      floodRisk: "HIGH",
    },
  },
  {
    slug: "akoka-hostel-room-block-b",
    title: "Akoka Hostel — single room (Block B)",
    description:
      "Managed student hostel run by a full-time caretaker. Rooms are single occupancy with a shared bathroom per floor, a study desk in every room, and a generator that runs from 6pm to 11pm. Cleaning of common areas is included in the service charge.",
    houseRules: "Hostel curfew is midnight. No cooking inside rooms; use the kitchen on each floor.",
    owner: "blessing",
    providerType: "CARETAKER",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    verificationNote: "Caretaker appointment letter and hostel registration confirmed by admin.",
    propertyType: "HOSTEL_ROOM",
    rentAmount: 120000,
    rentPeriod: "PER_SESSION",
    serviceCharge: 15000,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 1,
    furnishing: "FURNISHED",
    university: "UNILAG",
    campus: "akoka-campus",
    neighborhood: "akoka-lagos",
    areaName: "Akoka, Lagos",
    city: "Lagos",
    state: "Lagos",
    latitude: 6.5181,
    longitude: 3.3951,
    distanceKmToCampus: 0.5,
    addressLine: "Block B, Akoka Hostel, University Road",
    createdAtDaysAgo: 88,
    amenities: ["WATER", "ELECTRICITY", "GENERATOR", "SECURITY", "FENCED_COMPOUND", "SHARED_FACILITIES", "FURNITURE", "LAUNDRY", "KITCHEN"],
    features: ["Study desk in every room", "Generator 6pm to 11pm", "Daily cleaning of common areas", "Caretaker on site"],
    images: 4,
    condition: {
      electricityAvailable: true,
      generatorAvailable: true,
      waterSource: "PUBLIC_WATER",
      internetType: "WIFI",
      securityFeatures: ["SECURITY_PERSONNEL", "FENCED_COMPOUND", "CCTV"],
      electricityReliability: 4,
      waterReliability: 3,
      networkQuality: 3,
      roadCondition: 4,
      noiseLevel: 3,
      cleanliness: 4,
      floodRisk: "LOW",
    },
  },
  {
    slug: "mayfair-single-room-ile-ife",
    title: "Single room in Mayfair, Ile-Ife",
    description:
      "Single room in a family compound in Mayfair, ten minutes from the OAU main gate. Water is from a well, electricity runs on a shared meter, and the room is let unfurnished.",
    owner: "musa",
    providerType: "LANDLORD",
    status: "ACTIVE",
    verificationStatus: "PENDING",
    propertyType: "SINGLE_ROOM",
    rentAmount: 90000,
    rentPeriod: "PER_YEAR",
    cautionDeposit: 20000,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 1,
    furnishing: "UNFURNISHED",
    university: "OAU",
    campus: "main-campus",
    neighborhood: "mayfair-ile-ife",
    areaName: "Mayfair, Ile-Ife",
    city: "Ile-Ife",
    state: "Osun",
    latitude: 7.4901,
    longitude: 4.5263,
    distanceKmToCampus: 1.4,
    addressLine: "22 Mayfair Street, Ile-Ife",
    createdAtDaysAgo: 8,
    amenities: ["WATER", "ELECTRICITY", "FENCED_COMPOUND", "KITCHEN"],
    features: ["Shared kitchen with two other rooms", "Well water, boiling recommended"],
    images: 2,
    condition: {
      electricityAvailable: true,
      waterSource: "WELL",
      internetType: "MOBILE_NETWORK",
      securityFeatures: ["FENCED_COMPOUND"],
      electricityReliability: 2,
      waterReliability: 3,
      networkQuality: 3,
      roadCondition: 3,
      noiseLevel: 2,
      cleanliness: 3,
    },
  },
  {
    slug: "parakin-self-contain-ile-ife",
    title: "Tiled self-contain in Parakin, Ile-Ife",
    description:
      "Newly renovated self-contain with a tiled floor and bathroom, an en-suite kitchenette and a prepaid meter. On the Parakin side of Ife, about 1.6km from the OAU gate with a direct bike route.",
    owner: "musa",
    providerType: "LANDLORD",
    status: "ACTIVE",
    verificationStatus: "VERIFIED",
    verificationNote: "Identity and ownership verified; admin confirmed the prepaid meter during a site visit.",
    propertyType: "SELF_CONTAIN",
    rentAmount: 200000,
    rentPeriod: "PER_YEAR",
    cautionDeposit: 40000,
    bedrooms: 1,
    bathrooms: 1,
    maxOccupants: 2,
    furnishing: "PARTIALLY_FURNISHED",
    university: "OAU",
    campus: "main-campus",
    neighborhood: "parakin-ile-ife",
    areaName: "Parakin, Ile-Ife",
    city: "Ile-Ife",
    state: "Osun",
    latitude: 7.4721,
    longitude: 4.5011,
    distanceKmToCampus: 1.6,
    addressLine: "5 Parakin Road, Ile-Ife",
    createdAtDaysAgo: 34,
    amenities: ["WATER", "ELECTRICITY", "PREPAID_METER", "TILED_FLOOR", "EN_SUITE", "KITCHEN", "WARDROBE", "SECURITY"],
    features: ["Renovated in 2025", "Prepaid meter", "Built-in wardrobe"],
    images: 4,
    condition: {
      electricityAvailable: true,
      prepaidMeter: true,
      waterSource: "BOREHOLE",
      internetType: "MOBILE_NETWORK",
      securityFeatures: ["GATE"],
      electricityReliability: 3,
      waterReliability: 4,
      networkQuality: 3,
      roadCondition: 3,
      noiseLevel: 2,
      cleanliness: 4,
      floodRisk: "LOW",
    },
  },
  {
    slug: "samaru-2bedroom-flat-zaria",
    title: "2 bedroom flat near Samaru gate, Zaria",
    description:
      "Ground floor two bedroom flat in a quiet close behind the ABU Samaru gate. It is currently awaiting review by the StudentNest team before it appears in public search results.",
    owner: "musa",
    providerType: "LANDLORD",
    status: "PENDING_REVIEW",
    verificationStatus: "PENDING",
    propertyType: "FLAT",
    rentAmount: 700000,
    rentPeriod: "PER_YEAR",
    cautionDeposit: 150000,
    agencyFee: 35000,
    bedrooms: 2,
    bathrooms: 2,
    maxOccupants: 4,
    furnishing: "UNFURNISHED",
    university: "ABU",
    campus: "samaru-campus",
    neighborhood: "samaru-zaria",
    areaName: "Samaru, Zaria",
    city: "Zaria",
    state: "Kaduna",
    latitude: 11.1565,
    longitude: 7.6533,
    distanceKmToCampus: 1.1,
    addressLine: "7 Kofar Kuyambana Close, Samaru, Zaria",
    createdAtDaysAgo: 3,
    amenities: ["WATER", "ELECTRICITY", "PARKING", "KITCHEN", "FENCED_COMPOUND"],
    features: ["Ground floor, no stairs", "Large compound parking"],
    images: 3,
    condition: {
      electricityAvailable: true,
      waterSource: "BOREHOLE",
      internetType: "MOBILE_NETWORK",
      securityFeatures: ["FENCED_COMPOUND", "GATE"],
      electricityReliability: 3,
      waterReliability: 4,
      networkQuality: 2,
      roadCondition: 3,
      noiseLevel: 2,
      cleanliness: 4,
      floodRisk: "LOW",
    },
  },
];
