import type { SeedReview } from "./types";

/**
 * Demo reviews. Verification levels are only granted where the supporting data
 * exists (a VERIFIED_STAY row is backed by an admin-confirmed stay note, a
 * VERIFIED_REVIEWER row is backed by an inquiry the owner responded to).
 * One review is deliberately UNDER_REVIEW and one HIDDEN so the moderation
 * queue is not empty.
 */
export const REVIEWS: SeedReview[] = [
  {
    property: "sunrise-lodge-self-contain-awka",
    author: "chi",
    overall: 4,
    title: "Close enough to walk, and the meter is honest",
    body: "I stayed here for the whole session. The prepaid meter means you actually know what you are paying for power, which is rare in Awka. Water comes daily but pressure drops in the evening. The gate closes at 11pm, which suited me. A leaking tap took about three days to fix.",
    verification: "VERIFIED_STAY",
    status: "PUBLISHED",
    months: 10,
    stayFromDaysAgo: 300,
    response:
      "Thank you for the detailed feedback. We added a second pump, so evening pressure should improve. The caretaker now works to a 48 hour repair target.",
    daysAgo: 30,
    categoryOverrides: { WATER: 3, MAINTENANCE: 3, ELECTRICITY: 4, VALUE_FOR_MONEY: 4 },
  },
  {
    property: "sunrise-lodge-self-contain-awka",
    author: "kevin",
    overall: 5,
    title: "Best value self-contain I found in Ifite",
    body: "I walked to campus most days, which saved me transport money every week. The room was clean when I moved in and the compound is genuinely quiet at night. The landlord replied the same day I reported a faulty socket.",
    verification: "VERIFIED_REVIEWER",
    status: "PUBLISHED",
    months: 8,
    stayFromDaysAgo: 240,
    daysAgo: 14,
    categoryOverrides: { MAINTENANCE: 5, NOISE_ENVIRONMENT: 5, LANDLORD_BEHAVIOUR: 5 },
  },
  {
    property: "sunrise-lodge-self-contain-awka",
    author: "ndidi",
    overall: 2,
    title: "Water is the main problem",
    body: "The room itself is fine but there is not enough water for the number of tenants. I bought from vendors at least twice a week. The road in front also holds water during heavy rain.",
    verification: "UNVERIFIED",
    status: "UNDER_REVIEW",
    daysAgo: 4,
    categoryOverrides: { WATER: 1, ACCESSIBILITY: 2, VALUE_FOR_MONEY: 2 },
  },
  {
    property: "unizik-junction-shared-room-awka",
    author: "kevin",
    overall: 3,
    title: "Cheap and close, but noisy",
    body: "You cannot beat the price for the distance to the junction. Expect road noise until about 10pm and expect to queue for the bathroom in the morning. The generator only covers the corridor lights, not your room.",
    verification: "VERIFIED_REVIEWER",
    status: "PUBLISHED",
    months: 6,
    stayFromDaysAgo: 200,
    response: "We hear you on the morning rush — a second bathroom is being added to Block A during the break.",
    daysAgo: 44,
    categoryOverrides: { NOISE_ENVIRONMENT: 2, VALUE_FOR_MONEY: 5, ELECTRICITY: 2 },
  },
  {
    property: "cedar-court-2bedroom-flat-yaba",
    author: "tolu",
    overall: 4,
    title: "Inverter backup makes project work possible",
    body: "The inverter covers lights and fans, so I could keep working during outages. Estate security is real: there is a guard at the gate day and night. Agency fee plus service charge makes the first payment heavy, so budget for it.",
    verification: "VERIFIED_STAY",
    status: "PUBLISHED",
    months: 12,
    stayFromDaysAgo: 380,
    daysAgo: 60,
    categoryOverrides: { ELECTRICITY: 5, SECURITY: 5, VALUE_FOR_MONEY: 3, INTERNET: 5 },
  },
  {
    property: "cedar-court-2bedroom-flat-yaba",
    author: "bola",
    overall: 3,
    title: "Good flat, expensive to move into",
    body: "The flat is in good condition and Yaba is convenient, but between rent, caution and agency you need close to one and a half million for the first year. Water pressure on the second floor is weak in the morning.",
    verification: "VERIFIED_REVIEWER",
    status: "PUBLISHED",
    months: 5,
    stayFromDaysAgo: 150,
    daysAgo: 20,
    categoryOverrides: { VALUE_FOR_MONEY: 2, WATER: 3 },
  },
  {
    property: "bariga-studio-near-unilag",
    author: "bola",
    overall: 2,
    title: "The street floods in heavy rain",
    body: "The studio is small but furnished as described. My problem is the road: Pedro Road holds water badly and I could not leave the house during one storm. Power from the street is fairly stable.",
    verification: "UNVERIFIED",
    status: "UNDER_REVIEW",
    daysAgo: 6,
    categoryOverrides: { ACCESSIBILITY: 1, CLEANLINESS: 3, ELECTRICITY: 3 },
  },
  {
    property: "akoka-hostel-room-block-b",
    author: "tolu",
    overall: 4,
    title: "The caretaker actually maintains the place",
    body: "Block B is clean, the desks are proper desks, and the generator schedule is published and followed. Bathrooms are shared per floor so you will queue during exam period. Having a caretaker on site means small faults get fixed quickly.",
    verification: "VERIFIED_STAY",
    status: "PUBLISHED",
    months: 9,
    stayFromDaysAgo: 280,
    response: "Thanks Tolu. We are adding an extra bathroom attendant during exam weeks this session.",
    daysAgo: 55,
    categoryOverrides: { MAINTENANCE: 5, CLEANLINESS: 4, SECURITY: 4, NOISE_ENVIRONMENT: 3 },
  },
  {
    property: "akoka-hostel-room-block-b",
    author: "chi",
    overall: 3,
    title: "Safe, but the water schedule is tight",
    body: "Security is good and I never worried about my belongings. Water is pumped on a schedule rather than continuously, so you need a bucket habit. Common areas are cleaned daily.",
    verification: "VERIFIED_REVIEWER",
    status: "PUBLISHED",
    months: 4,
    stayFromDaysAgo: 120,
    daysAgo: 33,
    categoryOverrides: { WATER: 2, SECURITY: 5, CLEANLINESS: 4 },
  },
  {
    property: "mayfair-single-room-ile-ife",
    author: "yemi",
    overall: 3,
    title: "Cheap room, shared meter causes arguments",
    body: "Rent is genuinely low for Ife and the compound is quiet. Because the meter is shared you cannot see your own consumption, which created tension between tenants. Well water needs boiling.",
    verification: "UNVERIFIED",
    status: "PUBLISHED",
    months: 7,
    stayFromDaysAgo: 210,
    daysAgo: 26,
    categoryOverrides: { VALUE_FOR_MONEY: 4, WATER: 2, ELECTRICITY: 2 },
  },
  {
    property: "parakin-self-contain-ile-ife",
    author: "yemi",
    overall: 5,
    title: "The renovation is real and the prepaid meter is a relief",
    body: "Tiles, wardrobe and a working prepaid meter — everything in the photos matched what I found. Borehole water is clear and consistent. Ten minutes by bike to the gate.",
    verification: "VERIFIED_STAY",
    status: "PUBLISHED",
    months: 11,
    stayFromDaysAgo: 340,
    daysAgo: 40,
    categoryOverrides: { ELECTRICITY: 4, WATER: 5, CLEANLINESS: 5 },
  },
  {
    property: "parakin-self-contain-ile-ife",
    author: "grace",
    overall: 4,
    title: "Quiet and well finished",
    body: "I only visited twice before committing, but the room is as described. Network is decent on one provider and weak on another. Ask the landlord about the water tank schedule if you keep odd hours.",
    verification: "VERIFIED_REVIEWER",
    status: "PUBLISHED",
    months: 3,
    stayFromDaysAgo: 90,
    daysAgo: 11,
    categoryOverrides: { INTERNET: 3, NOISE_ENVIRONMENT: 5 },
  },
  {
    property: "kongo-single-room-zaria",
    author: "aisha",
    overall: 3,
    title: "The tanker schedule decides everything",
    body: "The room is affordable and the women-only section feels safe. Water comes by tanker twice a week so you must have your own storage. Power is off for long stretches in the harmattan season.",
    verification: "VERIFIED_STAY",
    status: "PUBLISHED",
    months: 10,
    stayFromDaysAgo: 320,
    daysAgo: 48,
    categoryOverrides: { WATER: 2, ELECTRICITY: 2, SECURITY: 4 },
  },
  {
    property: "kongo-single-room-zaria",
    author: "zainab",
    overall: 4,
    title: "Safe for female students",
    body: "I stayed two sessions here. The compound is well managed and the owner is responsive. Bring your own storage drums for water and you will be comfortable.",
    verification: "VERIFIED_REVIEWER",
    status: "PUBLISHED",
    months: 20,
    stayFromDaysAgo: 620,
    response: "Thank you Zainab. We added two more storage drums this month.",
    daysAgo: 70,
    categoryOverrides: { SECURITY: 5, WATER: 3, LANDLORD_BEHAVIOUR: 5 },
  },
  {
    property: "futa-gate-self-contain-akure",
    author: "grace",
    overall: 5,
    title: "Solar water heating actually works",
    body: "Seven minutes walk to the north gate. The inverter keeps the lights on during outages and the solar water heater is a real advantage in the dry season. Everything was clean on move-in day.",
    verification: "VERIFIED_STAY",
    status: "PUBLISHED",
    months: 12,
    stayFromDaysAgo: 400,
    daysAgo: 75,
    categoryOverrides: { ELECTRICITY: 5, WATER: 5, CLEANLINESS: 5, ACCESSIBILITY: 5 },
  },
  {
    property: "futa-gate-self-contain-akure",
    author: "halima",
    overall: 4,
    title: "Good room, slightly above average rent",
    body: "The finish quality justifies most of the price, though it sits at the top of what students pay around the gate. Fibre internet is available in the area, which helped a lot with assignments.",
    verification: "VERIFIED_REVIEWER",
    status: "PUBLISHED",
    months: 6,
    stayFromDaysAgo: 190,
    daysAgo: 18,
    categoryOverrides: { VALUE_FOR_MONEY: 3, INTERNET: 5 },
  },
  {
    property: "obanikoro-shared-room-akure",
    author: "grace",
    overall: 2,
    title: "Road access is poor in the rainy season",
    body: "Rent is cheap and the listing is honest about what the room is. The access road turns to mud and a bike will not always reach the gate. Borehole water is fine.",
    verification: "UNVERIFIED",
    status: "PUBLISHED",
    months: 5,
    stayFromDaysAgo: 160,
    daysAgo: 35,
    categoryOverrides: { ACCESSIBILITY: 1, VALUE_FOR_MONEY: 4, WATER: 4 },
  },
  {
    property: "ugbowo-3bedroom-apartment-benin",
    author: "halima",
    overall: 4,
    title: "Great for a group of four",
    body: "We split it four ways and it worked out cheaper than a hostel. The gated compound with CCTV felt secure and the treated borehole water is clear. Second floor means stairs on move-in day.",
    verification: "VERIFIED_STAY",
    status: "PUBLISHED",
    months: 11,
    stayFromDaysAgo: 350,
    daysAgo: 62,
    categoryOverrides: { SECURITY: 5, VALUE_FOR_MONEY: 4, WATER: 4 },
  },
  {
    property: "ugbowo-3bedroom-apartment-benin",
    author: "aisha",
    overall: 3,
    title: "The service charge is not optional",
    body: "Budget the service charge on top of rent — it is collected every year and covers the generator and security. The flat itself is spacious and the rooms have good cross ventilation.",
    verification: "VERIFIED_REVIEWER",
    status: "PUBLISHED",
    months: 8,
    stayFromDaysAgo: 250,
    daysAgo: 28,
    categoryOverrides: { VALUE_FOR_MONEY: 3, CLEANLINESS: 4 },
  },
  {
    property: "canaanland-self-contain-ota",
    author: "halima",
    overall: 4,
    title: "Shuttle access makes it practical",
    body: "Two minutes to the shuttle stop, which matters more than the raw distance. The wardrobe and kitchen are as shown. Power is shared across three rooms, so heavy appliances are discouraged.",
    verification: "VERIFIED_REVIEWER",
    status: "PUBLISHED",
    months: 7,
    stayFromDaysAgo: 220,
    daysAgo: 16,
    categoryOverrides: { ACCESSIBILITY: 5, ELECTRICITY: 3 },
  },
  {
    property: "sango-ota-2bedroom-bungalow",
    author: "chi",
    overall: 5,
    title: "Comfortable if you have transport",
    body: "Detached, private and well maintained. It is further from the gate than the Canaanland options, so you need the shuttle or a bike. Water pressure is strong and the garden is genuinely pleasant.",
    verification: "VERIFIED_STAY",
    status: "PUBLISHED",
    months: 10,
    stayFromDaysAgo: 310,
    daysAgo: 52,
    categoryOverrides: { WATER: 5, CLEANLINESS: 5, ACCESSIBILITY: 3 },
  },
  {
    property: "onuiyi-haven-room-nsukka-fully-let",
    author: "ndidi",
    overall: 3,
    title: "Decent room, now fully let",
    body: "I stayed here last session. Nothing fancy, but it was secure and the borehole water was reliable. Getting a room now means joining the waiting list.",
    verification: "VERIFIED_REVIEWER",
    status: "PUBLISHED",
    months: 9,
    stayFromDaysAgo: 430,
    daysAgo: 90,
    categoryOverrides: { WATER: 4, SECURITY: 4, VALUE_FOR_MONEY: 3 },
  },
  {
    property: "sunrise-lodge-self-contain-awka",
    author: "zainab",
    overall: 1,
    title: "Landlord is a thief and the whole street is bad",
    body: "Do not rent here. Everyone in Awka knows this landlord steals. The place is garbage and you will regret it.",
    verification: "UNVERIFIED",
    status: "HIDDEN",
    moderationReason:
      "Hidden pending review: unsupported accusation of a criminal offence plus abusive language. Not deleted — the student can edit and resubmit.",
    daysAgo: 9,
    categoryOverrides: { LANDLORD_BEHAVIOUR: 1 },
  },
  {
    property: "akoka-hostel-room-block-b",
    author: "grace",
    overall: 5,
    title: "Would take it again",
    body: "Everything in the listing was accurate, including the generator hours. The caretaker keeps records of repairs, which is unusual and made me trust the place. Bathrooms could be bigger.",
    verification: "VERIFIED_REVIEWER",
    status: "PUBLISHED",
    months: 6,
    stayFromDaysAgo: 180,
    daysAgo: 22,
    categoryOverrides: { MAINTENANCE: 5, LANDLORD_BEHAVIOUR: 5, CLEANLINESS: 4 },
  },
  {
    property: "unizik-junction-shared-room-awka",
    author: "aisha",
    overall: 4,
    title: "Good for the price",
    body: "I only stayed one semester but the room was as advertised and the caretaker sorted a broken window latch quickly. The well water tastes off, so most people buy drinking water.",
    verification: "VERIFIED_REVIEWER",
    status: "PUBLISHED",
    months: 4,
    stayFromDaysAgo: 140,
    daysAgo: 24,
    categoryOverrides: { WATER: 3, MAINTENANCE: 4, VALUE_FOR_MONEY: 5 },
  },
];
